name: onepress
description: A new News application for onepress Co.LTE

version: 1.0.5+5

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen: ^1.2.0
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:
  scoped_model: ^1.0.1
  dio: ^3.0.1
  cupertino_icons: ^0.1.3
  flutter_redux: ^0.6.0
  shared_preferences: ^0.5.6
  flutter_swiper: ^1.1.6
  transparent_image: ^1.0.0
  html: ^0.14.0+3
  esys_flutter_share: ^1.0.2
  random_pk: any
  shimmer: ^1.0.1
  flutter_slidable: ^0.5.4
  flutter_rating: ^0.0.2
  http: ^0.12.0+3
  get_it: ^3.1.0
  firebase_messaging: ^6.0.9
  onesignal_flutter: ^2.3.1
  admob_flutter: ^0.3.4
  font_awesome_flutter: ^8.5.0
  image_picker: ^0.6.2+3
  timeago: ^2.0.24
  youtube_player: ^3.5.0
  cached_network_image: ^2.0.0-rc.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  #  fonts:
  #    - family: Tajawal
  #      fonts:
  #        - asset: assets/fonts/tajawal_regular.ttf
  fonts:
    - family: jazeera
      fonts:
        - asset: assets/fonts/jazeera-regular.ttf
        - asset: assets/fonts/jazeera-light.ttf
          weight: 200
        - asset: assets/fonts/jazeera-bold.ttf
          weight: 700
  assets:
    - assets/logo.png
    - assets/stack_bg.png
    - assets/logo_login.png
    - assets/place_holder_big.png
    - assets/IlustrasiMessage.png